```vue
<script setup>
import { ref, onMounted } from 'vue';
import * as d3 from 'd3';
import Circos from 'circos';
import { readFile } from '@/utils/server'; // 引入封装的 readFile API 调用
import { reduceData, reduceData_Position, transform_startend_position, gieStainColor } from '@/components/Center/utils_circos.js';
const chart = ref(null);
onMounted(async () => {
  try {
    //获取参考基因组文件
    let hg19 = await d3.json('/data/hg19.json')
    let cytobands = await d3.csv('/data/cytobands.csv');

    //设置画布
    let chartWidth = chart.value.clientWidth;
    let width = chartWidth;
    let innerRadius = chartWidth/2-100+10;
    let outerRadius = chartWidth/2-100+50;

    //初始化circos
    const circos = new Circos({
      container: chart.value,
      width: width,
      height: width,
    });
    circos.layout(
      hg19,
      {
        innerRadius: innerRadius,
        outerRadius: outerRadius,
        labels: {
          display: true,
          radialOffset: 30,
          color: "black",
          size: 10
        },
        ticks: {
          display: true,
          color: 'grey',
          labels: true,
          labelSuffix: 'Mb',//百万级别
          labelDenominator: 5000000,
          spacing: 5000000,
          labelSize: 5,
          labelColor: 'grey',

        },
      }
    );
    //绘制参考基因组染色体
    let highlightData = cytobands.map(function (d) {
      return {
        block_id: d.id,
        start: parseInt(d.start),
        end: parseInt(d.end),
        gieStain: d.gieStain
      }
    })

    let highlightConfig = {
      innerRadius: innerRadius,
      outerRadius: outerRadius,
      opacity: 1,
      color: function (d) {
        return gieStainColor[d.gieStain]
      }
    }

    circos.highlight('highlight', highlightData, highlightConfig)
    //The above are some basic configurations, 
    //code generated by llm should be written below

    /**
     * Purple connection lines
     * Linking regions where Chromosome and Chromosome.1 columns have different values.
     * Data source: file3.csv.
     */
    let lines = await d3.csv('/data/data_back/id_002/file.csv')
    
    //将lines中chr1中的“chr”去掉
    lines = lines.map((item) => {
      return {
        ...item,
        chr1: item["chr1"].replace("chr", ""),
        chr2: item["chr2"].replace("chr", "")
      }
    })

    //Draw me a chord graph using the data from file1,and assign different colors to the wires according to the color value
    let step1 = lines.map((item) => {
      return {
        source: {
          id: item["chr1"],
          start: Number(item["start1"]),
          end: Number(item["end1"])
        },
        target: {
          id: item["chr2"],
          start: Number(item["start2"]),
          end: Number(item["end2"])
        }
      }
    })
    circos.chords('lines', step1, {
      color: "#800080",
      opacity: 0.8,
    })



    //过滤的规则：
    // color字段范围 是0-300
    // 颜色映射规则是：
    // 2黄
    // 4紫
    // 0-50 对应#ffffb3
    // 50-100 对应#ffff65
    // 100-150 对应#e3d5fa
    // 150-200 对应#c1a8f4
    // 200-250 对应#7d5be8
    // 250-300 对应#422ddf
    // 透明度都是0.8
    let lines_1 = lines.filter((item) => {
      if (item["color"] >= 0 && item["color"] <= 50) {
        return true;
      } else {
        return false;
      }
    })
    console.log(`lines_1: ${lines_1}`)
    let lines_2 = lines.filter((item) => {
      if (item["color"] >= 50 && item["color"] <= 100) {
        return true;
      } else {
        return false;
      }
    })  
    let lines_3 = lines.filter((item) => {
      if (item["color"] >= 100 && item["color"] <= 150) {
        return true;
      } else {
        return false;
      }
    })
    let lines_4 = lines.filter((item) => {
      if (item["color"] >= 150 && item["color"] <= 200) {
        return true;
      } else {
        return false;
      }
    })
    let lines_5 = lines.filter((item) => {
      if (item["color"] >= 200 && item["color"] <= 250) {
        return true;
      } else {
        return false;
      }
    })
    let lines_6 = lines.filter((item) => {
      if (item["color"] >= 250 && item["color"] <= 300) {
        return true;
      } else {
        return false;
      }
    })
    lines_1 = lines_1.map((item) => {
      return {
        source: {
          id: item["chr1"],
          start: Number(item["start1"]),
          end: Number(item["end1"])
        },
        target: { 
          id: item["chr2"],
          start: Number(item["start2"]),
          end: Number(item["end2"])
        }
      }
    })
    circos.chords('lines_1', lines_1, {
      color: "#ffffb3",
      opacity: 0.8,
    })

    lines_2 = lines_2.map((item) => {
      return {
        source: {
          id: item["chr1"],
          start: Number(item["start1"]),
          end: Number(item["end1"])
        }, 
        target: {
          id: item["chr2"],
          start: Number(item["start2"]),
          end: Number(item["end2"]) 
        }
      } 
    })
    lines_3 = lines_3.map((item) => {
      return {
        source: {
          id: item["chr1"],
          start: Number(item["start1"]),
          end: Number(item["end1"])
        }, 
        target: {
          id: item["chr2"],
          start: Number(item["start2"]),
          end: Number(item["end2"]) 
        }
      } 
    })
    lines_4 = lines_4.map((item) => {
      return {
        source: {
          id: item["chr1"],
          start: Number(item["start1"]),
          end: Number(item["end1"])
        }, 
        target: {
          id: item["chr2"],
          start: Number(item["start2"]),
          end: Number(item["end2"]) 
        }
      } 
    })
    lines_5 = lines_5.map((item) => {
      return {
        source: {
          id: item["chr1"],
          start: Number(item["start1"]),
          end: Number(item["end1"])
        }, 
        target: {
          id: item["chr2"],
          start: Number(item["start2"]),
          end: Number(item["end2"]) 
        }
      } 
    })
    lines_6 = lines_6.map((item) => {
      return {
        source: {
          id: item["chr1"],
          start: Number(item["start1"]),
          end: Number(item["end1"])
        }, 
        target: {
          id: item["chr2"],
          start: Number(item["start2"]),
          end: Number(item["end2"]) 
        }
      } 
    })
    circos.chords('lines_2', lines_2, {
      color: "#ffff65",
      opacity: 0.8,
      radius: .6
    })
    circos.chords('lines_3', lines_3, {
      color: "#e3d5fa",
      radius: .6,
      opacity: 0.8
    })
    circos.chords('lines_4', lines_4, {
      color: "#c1a8f4",
      radius: .6,
      opacity: 0.8,
    })
    circos.chords('lines_5', lines_5, {
      color: "#7d5be8",
      radius: .6,
      opacity: 0.8
    })
    circos.chords('lines_6', lines_6, {
      color: "#422ddf",
      radius: .6,
      opacity: 0.8
    })

    let histogram = await d3.csv('/data/data_back/id_002/file2.csv')
    histogram = histogram.map((item) => {
      return {
        ...item,
        block_id: item["block_id"].replace("chr", "")
      }
    })
    histogram=histogram.map((item) => {
      return {
        block_id:item["block_id"],
        start:Number(item["start"]),
        end:Number(item["end"]),
        value:Number(item["value"])
      }
    })
    //大于0的
    let histogram_1 = histogram.filter((item) => {
      if (item["value"] > 0) {
        return true;
      } else {
        return false;
      }
    })
    
    //小于0的
    let histogram_2 = histogram.filter((item) => {
      if (item["value"] < 0) {
        return true;
      } else {
        return false;
      }
    })
    console.log(histogram_1)
    circos.histogram('histogram_1', histogram_1, {
      innerRadius: .8,
      outerRadius: 1,
      color: "#f97794",
      // opacity: 0.8
    })
    circos.histogram('histogram_2', histogram_2, {
      innerRadius:.6,
      outerRadius: .8,
      color: "#44c7fe",
      // opacity: 0.8,
      direction: "in"
    })

    circos.render();
  } catch (err) {
    console.error('Error fetching or processing data:', err);
  }
  
});
</script>

<!-- The following code should not be changed -->
<template>
  <div ref="chart"></div>
</template>

<style scoped>
#chart {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%; 
  height: 100%;
}
</style>
```