<script setup>
import { ref, onMounted } from 'vue';
import * as d3 from 'd3';
import Circos from 'circos';
import { readFile } from '@/utils/server'; // 引入封装的 readFile API 调用
import { delete_overflow, reduceData, reduceData_Position, transform_startend_position, gieStainColor } from './utils_circos.js';
onMounted(async () => {
  try {
    //获取参考基因组文件
    let hg19 = await d3.json('/data/hg19.json')
    let cytobands = await d3.csv('/data/cytobands.csv');

    //设置画布
    let chartWidth = document.getElementById('chart').clientWidth;
    let width = chartWidth;
    let innerRadius = chartWidth / 2 - 100;
    let outerRadius = chartWidth / 2 - 100 + 50;

    //初始化circos
    const circos = new Circos({
      container: `#chart`,
      width: width,
      height: width,
    });
    circos.layout(
      hg19,
      {
        innerRadius: innerRadius,
        outerRadius: outerRadius,
        labels: {
          display: true,
          radialOffset: 60,
          color: "black",
          size: 10
        },
        ticks: {
          display: true,
          color: 'grey',
          labels: false,
          labelSuffix: 'Mb',//百万级别
          labelDenominator: 5000000,
          spacing: 5000000,
          labelSize: 5,
          labelColor: 'grey',

        },
      }
    );
    //绘制参考基因组染色体
    let highlightData = cytobands.map(function (d) {
      return {
        block_id: d.id,
        start: parseInt(d.start),
        end: parseInt(d.end),
        gieStain: d.gieStain
      }
    });

    let highlightConfig = {
      innerRadius: innerRadius,
      outerRadius: outerRadius,
      opacity: .7,
      color: function (d) {
        return gieStainColor[d.gieStain]
      }
    }

    circos.highlight('highlight', highlightData, highlightConfig)
    //The above are some basic configurations, 
    //code generated by llm should be written below

    /**
     * 绿色柱状图
     * 插入和缺失（绿色矩形）：
        浅绿色矩形：验证的插入（来自附表2）。
        深绿色矩形：验证的缺失（来自附表2）。  
        用file2，Insertion类型画一个环形柱状图的track，深绿色，Validation_status类型画一个环形柱状图的track，浅绿色
     */

    let level2 = await readFile('id_001/file2.csv');
    //第一步：条件过滤
    let level2_1 = level2.filter((item) => {
      if (item["Type"] == "Insertion" && item["Validation_status"] != "") {
        return true;
      } else {
        return false;
      }
    })
    let level2_2 = level2.filter((item) => {
      if (item["Type"] == "Deletion" && item["Validation_status"] != "") {
        return true;
      } else {
        return false;
      }
    })

    //第二步：组合成绘图需要的格式
    level2_1 = reduceData(level2_1, hg19, 10000000)
    level2_2 = reduceData(level2_2, hg19, 10000000)

    //第三步：绘图
    circos.histogram('level2_1', level2_1, {
      innerRadius: 0.85,
      outerRadius: 0.90,
      color: "darkgreen",
      opacity: 1.0
    })
    circos.histogram('level2_2', level2_2, {
      innerRadius: 0.90,
      outerRadius: 0.95,
      color: "lightgreen",
      opacity: 1.0
    })

    /**
     * 橙色柱状图
     * 体细胞突变的密度（橙色条）：
        浅橙色条：异型合子的单核苷酸变异（heterozygous）。
        每10 Mb的密度计算来自附表1。
        深橙色条：纯合子的单核苷酸变异（homozygous）。
     */

    //第0步：拿文件
    let level3 = await readFile('id_001/file1.csv');

    //第一步：条件过滤
    let level3_1 = level3.filter((item) => {
      if (item["Zygosity"] == "het") {
        return true;
      } else {
        return false;
      }
    })
    let level3_2 = level3.filter((item) => {
      if (item["Zygosity"] == "hom") {
        return true;
      } else {
        return false;
      }
    })

    //第二步：组合成绘图需要的格式
    level3_1 = reduceData_Position(level3_1, hg19, 10000000)
    level3_2 = reduceData_Position(level3_2, hg19, 10000000)

    //画图
    circos.histogram('level3_1', level3_1, {
      innerRadius: 0.70,
      outerRadius: 0.80,
      color: "#faa95d",
      opacity: 1.0
    })
    circos.histogram('level3_2', level3_2, {
      innerRadius: 0.60,
      outerRadius: 0.70,
      color: "#f0761e",
      opacity: 1.0,
      direction: 'in'
    })

    /**
     * 编码突变（彩色方块）：
        不同颜色表示不同类型的突变：
          灰色：沉默突变（Silent）。
     */
    let level4 = await readFile('id_001/file4.csv');
    //第一步：条件过滤
    let level4_1 = level4.filter((item) => {
      if (item["Effect"] == "Silent") {
        return true;
      } else {
        return false;
      }
    })
    let level4_3 = level4.filter((item) => {
      if (item["Effect"] == "Nonsense") {
        return true;
      } else {
        return false;
      }
    })

    //第二步：组合成绘图需要的格式
    level4_1 = level4_1.map((item) => {
      return {
        block_id: item["Chromosome"],
        position: item["Position"],
        value: 1
      }
    })
    level4_3 = level4_3.map((item) => {
      return {
        block_id: item["Chromosome"],
        position: item["Position"],
        value: 1
      }
    })

    circos.scatter('level4_1', level4_1, {
      innerRadius: 0.50,
      outerRadius: 0.60,
      color: "gray",
      fill: "gray",
      size: 3,
      strokeColor: "none"
    })
    circos.scatter('level4_3', level4_3, {
      innerRadius: 0.40,
      outerRadius: 0.50,
      color: "red",
      fill: "red",
      size: 3,
      strokeColor: "none"
    })

    /**
     * 蓝紫色线
     * 杂合性丢失区域（LOH）（蓝紫色线条）：
          显示了在基因组中出现的杂合性丢失区域。
          数据来源于附表6。
     */
    let level6 = await readFile('id_001/file6.csv');
    //第一步：组合成绘图需要的格式
    level6 = level6.map((item) => {
      return {
        'block_id': item["id"],
        'start': Number(item["Start"]),
        'end': Number(item["End"]),
        'value': 1
      }
    });

    //第二步：画图
    circos.heatmap('level6', level6, {
      innerRadius: 0.30,
      outerRadius: 0.40,
      color: "pink", // 粉色
      opacity: 1.0,
    })

    /**
     * 绿色连线
     * 重排（绿色线条）：
        绿色线条：验证的染色体内重排（intrachromosomal rearrangements）。
        数据来源为附表3。
     */
    let level7 = await readFile('id_001/file3.csv');
    let level7_1 = level7.filter((item) => {
      if (item["Chromosome"] == item["Chromosome.1"]) {
        return true;
      } else {
        return false;
      }
    })

    level7_1 = level7_1.map((item) => {
      return {
        source: {
          id: item["Chromosome"],
          start: Number(item["Position"]),
          end: Number(item["Position"]) + 10000000
        },
        target: {
          id: item["Chromosome.1"],
          start: Number(item["Position.1"]),
          end: Number(item["Position.1"]) + 10000000
        }
      }
    })

    circos.chords('level7_1', level7_1, {
      color: "green",
      radius: 0.25,
    })

    circos.render();

    console.log("渲染完成！");
    let allDom = document.querySelectorAll('.all')[0]
    console.log(allDom);
    // 获取所有第一层子div
    let children = allDom.children;
    console.log("children", children);
    // 遍历每个子div并添加hover事件监听

    for (let child of children) {
      child.addEventListener('mouseenter', () => {
        child.style.cursor = 'pointer';
        // 获取 g 元素的边界信息
        let rect = child.getBoundingClientRect();

        // 获取宽度和高度
        let width = rect.width;
        let height = rect.height;

        console.log(`g元素的宽度：${width}`);
        console.log(`g元素的高度：${height}`);
        // 创建一个SVG圆圈元素
        let circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
        circle.setAttribute("cx", 0);
        circle.setAttribute("cy", 0);
        circle.setAttribute("r", width/2);
        circle.setAttribute("stroke", "#d9d9d9");
        circle.setAttribute("fill", "none"); 
        circle.setAttribute("stroke-width", "1");
        circle.classList.add("circle-hover");
        
        // 将圆圈插入到child元素的第一个位置
        child.insertBefore(circle, child.firstChild);

        child.style.transform = 'scale(1.01)';
        child.style.stroke = '#ffff00';
        child.style.strokeWidth = '2';
        child.style.filter = 'drop-shadow(0 0 5px #ffff00)';
        child.style.transition = 'all 0.3s ease';
      });

      child.addEventListener('mouseleave', () => {
        // 获取所有circle-hover元素
        let circles = child.getElementsByClassName('circle-hover');
        // 删除所有circle-hover元素
        while(circles.length > 0) {
            circles[0].remove();
        }
        child.style.transform = 'scale(1)';
        child.style.stroke = 'none';
        child.style.strokeWidth = '0';
        child.style.filter = 'none';
      });
    }


  } catch (err) {
    console.error('Error fetching or processing data:', err);
  }
});

</script>

<!-- The following code should not be changed -->
<template>
  <div id="chart"></div>
</template>

<style scoped>
#chart {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
}
</style>