
<script setup>
import { ref, onMounted } from 'vue';
import * as d3 from 'd3';
import Circos from 'circos';
import { readFile } from '@/utils/server'; // 引入封装的 readFile API 调用
import { reduceData, reduceData_Position, transform_startend_position, gieStainColor } from '@/components/Center/utils_circos.js';
const chart = ref(null);
onMounted(async () => {
  try {
    //获取参考基因组文件
    let hg19 = await d3.json('/data/hg19.json')
    let cytobands = await d3.csv('/data/cytobands.csv');

    //设置画布
    let chartWidth = chart.value.clientWidth;
    let width = chartWidth;
    let innerRadius = chartWidth/2-100;
    let outerRadius = chartWidth/2-100+50;

    //初始化circos
    const circos = new Circos({
      container: chart.value,
      width: width,
      height: width,
    });
    circos.layout(
      hg19,
      {
        innerRadius: innerRadius,
        outerRadius: outerRadius,
        labels: {
          display: true,
          radialOffset: 60,
          color: "black",
          size: 10
        },
        ticks: {
          display: true,
          color: 'grey',
          labels: false,
          labelSuffix: 'Mb',//百万级别
          labelDenominator: 5000000,
          spacing: 5000000,
          labelSize: 5,
          labelColor: 'grey',

        },
      }
    );
    //绘制参考基因组染色体
    let highlightData = cytobands.map(function (d) {
      return {
        block_id: d.id,
        start: parseInt(d.start),
        end: parseInt(d.end),
        gieStain: d.gieStain
      }
    })

    let highlightConfig = {
      innerRadius: innerRadius,
      outerRadius: outerRadius,
      opacity: .7,
      color: function (d) {
        return gieStainColor[d.gieStain]
      }
    }

    circos.highlight('highlight', highlightData, highlightConfig)
    //The above are some basic configurations, 
    //code generated by llm should be written below


    /**
     * 深绿色柱状图
     */
    let level2 = await readFile('id_001/file2.csv');
    //第一步：条件过滤
    let level2_1 = level2.filter((item) => {
      if (item["Type"] == "Insertion" && item["Validation_status"] != "") {
        return true;
      } else {
        return false;
      }
    })

    //第二步：组合成绘图需要的格式
    level2_1 = reduceData(level2_1, hg19, 10000000)

    //第三步：绘图
    circos.histogram('level2_1', level2_1, {
      innerRadius: 0.76,
      outerRadius: 0.85,
      color: "#006400",
      opacity: 1.0
    })

    circos.render();
  } catch (err) {
    console.error('Error fetching or processing data:', err);
  }
});
</script>

<!-- The following code should not be changed -->
<template>
  <div ref="chart"></div>
</template>

<style scoped>
#chart {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%; 
  height: 100%;
}
</style>
