
<script setup>
import { ref, onMounted } from 'vue';
import * as d3 from 'd3';
import Circos from 'circos';
import { readFile } from '@/utils/server'; // 引入封装的 readFile API 调用
import { reduceData, reduceData_Position, transform_startend_position, gieStainColor } from '@/components/Center/utils_circos.js';
const chart = ref(null);
onMounted(async () => {
  try {
    //获取参考基因组文件
    let hg19 = await d3.json('/data/hg19.json')
    let cytobands = await d3.csv('/data/cytobands.csv');

    //设置画布
    let chartWidth = chart.value.clientWidth;
    let width = chartWidth;
    let innerRadius = chartWidth / 2 - 100;
    let outerRadius = chartWidth / 2 - 100 + 50;

    //初始化circos
    const circos = new Circos({
      container: chart.value,
      width: width,
      height: width,
    });
    circos.layout(
      hg19,
      {
        innerRadius: innerRadius,
        outerRadius: outerRadius,
        labels: {
          display: true,
          radialOffset: 60,
          color: "black",
          size: 10
        },
        ticks: {
          display: true,
          color: 'grey',
          labels: false,
          labelSuffix: 'Mb',//百万级别
          labelDenominator: 5000000,
          spacing: 5000000,
          labelSize: 5,
          labelColor: 'grey',

        },
      }
    );
    //绘制参考基因组染色体
    let highlightData = cytobands.map(function (d) {
      return {
        block_id: d.id,
        start: parseInt(d.start),
        end: parseInt(d.end),
        gieStain: d.gieStain
      }
    })

    let highlightConfig = {
      innerRadius: innerRadius,
      outerRadius: outerRadius,
      opacity: .7,
      color: function (d) {
        return gieStainColor[d.gieStain]
      }
    }

    circos.highlight('highlight', highlightData, highlightConfig)
    //The above are some basic configurations, 
    //code generated by llm should be written below

    // Adjust the existing tracks to make space for the new track
    let level2 = await readFile('id_001/file2.csv');
    // Step 1: Adjust existing dark-green bar chart
    let level2_1 = level2.filter((item) => {
      if (item["Type"] == "Insertion" && item["Validation_status"] != "") {
        return true;
      } else {
        return false;
      }
    });

    level2_1 = reduceData(level2_1, hg19, 10000000);

    circos.histogram('level2_1', level2_1, {
      innerRadius: 0.70,
      outerRadius: 0.80,
      color: "darkgreen",
      opacity: 1.0
    });

    // Add new light-green bar chart track
    // let level2 = await readFile('id_001/file2.csv');
    // Step 1: Condition filtering
    let level2_2 = level2.filter((item) => {
      if (item["Type"] == "Deletion" && item["Validation_status"] != "") {
        return true;
      } else {
        return false;
      }
    });

    // Step 2: Format data for plotting
    level2_2 = reduceData(level2_2, hg19, 10000000);

    // Step 3: Plotting
    circos.histogram('level2_2', level2_2, {
      innerRadius: 0.60,
      outerRadius: 0.70,
      color: "lightgreen",
      opacity: 1.0
    });

    // Red scatter plot for Nonsense mutation
    let level4 = await readFile('id_001/file4.csv');
    // Filter rows where Effect is Nonsense
    let level4_3 = level4.filter((item) => {
      if (item["Effect"] == "Nonsense") {
        return true;
      } else {
        return false;
      }
    });
    // Format data for plotting
    level4_3 = level4_3.map((item) => {
      return {
        block_id: item["Chromosome"],
        position: item["Position"],
        value: 1
      }
    });
    // Plot
    circos.scatter('level4_3', level4_3, {
      innerRadius: 0.50,
      outerRadius: 0.60,
      color: "red",
      fill: "red",
      size: 3,
      strokeColor: "none"
    });

    // Blue line chart for Copy number variation
    let level5 = await readFile('id_001/file5.csv');
    // Format data for plotting
    level5 = transform_startend_position(level5, "Copy number");
    // Plot
    circos.line('level5', level5, {
      innerRadius: 0.35,
      outerRadius: 0.50,
      color: "#5979ae",
      axes: [
        {
          spacing: 2,
          color: "gray",
          thickness: .3,
          opacity: .5
        }
      ],
      backgrounds: [
        {
          color: "#d6d6d6"
        }
      ]
    });

    //新增红色热图的代码
    let level6 = await readFile('id_001/file6.csv');
    //第一步：组合成绘图需要的格式
    level6 = level6.map((item) => {
      return {
        'block_id': item["id"],
        'start': Number(item["Start"]),
        'end': Number(item["End"]),
        'value': 1
      }
    });
    //第二步：画图
    circos.heatmap('level6', level6, {
      innerRadius: 0.25,
      outerRadius: 0.35,
      color: "red",
      opacity: 1.0
    });

    circos.render();
  } catch (err) {
    console.error('Error fetching or processing data:', err);
  }
});
</script>

<!-- The following code should not be changed -->
<template>
  <div ref="chart"></div>
</template>

<style scoped>
#chart {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%; 
  height: 100%;
}
</style>
